name: rag-csd
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Python
  - python>=3.8,<3.11
  
  # Core scientific computing
  - numpy>=1.20.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  
  # Machine learning and deep learning
  - pytorch>=1.10.0
  - pytorch-cuda=11.8  # For CUDA support, remove if CPU-only
  - transformers>=4.18.0
  - sentence-transformers>=2.2.0
  - tokenizers>=0.12.0
  
  # Vector databases and similarity search
  - faiss-cpu>=1.7.2  # Use faiss-gpu for GPU support
  
  # Data processing and NLP
  - nltk>=3.6.5
  - pyyaml>=6.0
  - tqdm>=4.62.0
  - requests>=2.26.0
  
  # Document processing
  - python-docx>=0.8.11
  - openpyxl>=3.0.10
  
  # Visualization and monitoring
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - plotly>=5.0.0
  - dash>=2.0.0
  - tensorboard>=2.8.0
  
  # Web framework (for API)
  - fastapi>=0.78.0
  - uvicorn>=0.17.0
  - pydantic>=1.9.0
  
  # Development tools
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - ipython>=8.2.0
  - black>=22.3.0
  - isort>=5.10.0
  - flake8>=4.0.0
  - mypy>=0.950
  - pylint>=2.13.0
  
  # Testing
  - pytest>=7.0.0
  - pytest-cov>=3.0.0
  - pytest-benchmark>=3.4.0
  - hypothesis>=6.46.0
  
  # Profiling and debugging
  - memory-profiler>=0.60.0
  - line-profiler>=3.5.0
  
  # Documentation
  - sphinx>=4.5.0
  - sphinx-rtd-theme>=1.0.0
  
  - pip
  - pip:
    # Packages not available via conda
    - PyPDF2>=3.0.0
    - wandb>=0.12.0
    - nbsphinx>=0.8.0
    - sphinx-autodoc-typehints>=1.17.0
    - pre-commit>=2.18.0
    - pudb>=2022.1